services:
  server:
    container_name: peek-rate-server
    #Dev mode
    # build:
    #   context: .
    #   dockerfile: ./docker/Dockerfile
    #   target: dev
    # command: ['pnpm', 'start:dev']
    #Prod mode
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      target: prod
    command: ['pnpm', 'start:prod']
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env.production
    environment:
      - AUTO_SEED=true # Set to false to disable auto-seeding
    ports:
      - $PORT:3000
    volumes:
      - ./logs:/app/logs # Persist logs on host

  database:
    container_name: peek-rate-database
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: $DB_USERNAME
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:5432
    env_file:
      - .env.production
    volumes:
      - postgres_data:/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: peek-rate-pgadmin
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: hqh@example.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 5050:80
    restart: always

  redis:
    container_name: peek-rate-redis # host connect redis-insight
    image: redis:8.2.3-alpine
    restart: always
    command: sh /redis-init.sh
    ports:
      - $REDIS_PORT:6379
    volumes:
      - redis_data:/data
      - ./redis-init.sh:/redis-init.sh:ro
    env_file:
      - .env.production
    environment:
      - REDIS_USERNAME=$REDIS_USERNAME
      - REDIS_PASSWORD=$REDIS_PASSWORD

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight:latest
    ports:
      - 5540:5540
    volumes:
      - redis_insight:/data
    restart: always
    depends_on:
      - redis
    healthcheck:
      test: ['CMD-SHELL', 'curl --fail http://localhost:5540 || exit 1']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  redis_insight:
    driver: local

networks:
  default:
    name: peek-rate-network
